from __future__ import annotations

from pathlib import Path

from .input import clean_answer
from .model import Candidate

FALLBACK_WORDS = """
ABLE ACHE ACID ACME ACRE ACTOR ADAGE ADAPT ADDED ADMIT ADOPT ADORE ADULT
AFTER AGAIN AGENT AGILE AGREE AHEAD AISLE ALARM ALBUM ALERT ALIEN ALIKE ALIVE
ALLEY ALLOW ALONE ALONG ALTER AMBER AMEND AMONG ANGEL ANGER ANGLE ANKLE
APPLE APRON ARENA ARGUE ARISE ARMED ARROW ASIDE ASSET ATLAS AUDIO AUNTIE
AVOID AWAKE AWARD AWARE BACON BADGE BAKER BASIC BASIL BEACH BEARD BEAST
BEGIN BELOW BENCH BERRY BIRTH BLACK BLADE BLANK BLEND BLESS BLOCK BLOOM
BOARD BOAST BONUS BOUND BRAIN BRAVE BREAD BREAK BRICK BRIDE BRING BROAD
BROOK BROWN BRUSH BUNCH CABIN CABLE CANDY CANOE CARRY CATCH CAUSE CHAIR
CHALK CHARM CHART CHASE CHEER CHESS CHEST CHILD CHILL CHOIR CIVIC CLAIM
CLASS CLEAN CLEAR CLERK CLIFF CLIMB CLOCK CLOSE CLOTH CLOUD COACH COAST
COMET COMIC CORAL COUNT COURT COVER CRAFT CRANE CRASH CREAM CRISP CROSS
CROWN DANCE DATED DEALT DECOR DELAY DEPOT DIARY DINER DOZEN DRAFT DREAM
DRESS DRIFT DRINK DRIVE EARLY EARTH EASEL EATEN EIGHT ELBOW ELDER ELECT
EMPTY ENJOY ENTER ENTRY EQUAL ERROR EVENT EVERY EXACT EXTRA FAITH FALSE
FANCY FAULT FAVOR FEAST FIELD FINAL FIRST FLAIR FLEET FLOOR FLOUR FOCUS
FORCE FRESH FRONT FROST FRUIT FUNNY GIANT GIVEN GLASS GLOBE GRACE GRADE
GRAIN GRAND GRANT GRAPE GRAPH GRASS GREAT GREEN GROUP GUARD GUEST GUIDE
HAPPY HEART HOBBY HONEY HONOR HOTEL HOUSE HUMAN HUMOR HURRY IMAGE INDEX
INNER INPUT ISSUE JELLY JOINT JUDGE JUICE KNIFE LABEL LARGE LASER LATER
LAUGH LAYER LEARN LEAST LEMON LEVEL LIGHT LIMIT LOCAL LODGE LOGIC LOOSE
LOVER LUCKY LUNCH MAGIC MAJOR MAPLE MARCH MATCH MAYBE MEDAL MERIT MERRY
METAL MINOR MODEL MONEY MONTH MORAL MOTOR MOUNT MOVIE MUSIC NEEDS NEVER
NIGHT NOBLE NOISE NORTH NOVEL NURSE OCEAN OFFER OLIVE ONION OPERA ORBIT
ORDER ORGAN OTHER OUTER OWNER PAINT PANEL PAPER PARTY PASTA PATCH PEACH
PEARL PHONE PIANO PILOT PIZZA PLACE PLAIN PLANE PLANT PLATE POINT POUND
POWER PRESS PRICE PRIDE PRIME PRINT PRIZE PROOF PROUD PULSE QUEEN QUICK
QUIET RADIO RANCH RANGE RAPID RATIO REACH READY REALM RIVER ROAST ROBIN
ROUND ROUTE ROYAL RUGBY SALAD SCALE SCENE SCOPE SCORE SCOUT SCRAP SEASON
SEVEN SHADE SHARE SHEET SHELF SHINE SHIRT SHORE SHORT SIGHT SINCE SKILL
SLATE SLEEP SLICE SMALL SMART SMILE SOLAR SOUND SOUTH SPACE SPARE SPARK
SPEAK SPEED SPICE SPILL SPORT STACK STAGE STAIR STAND START STEAM STEEL
STICK STONE STORE STORM STORY STRAW STYLE SUGAR SUNNY TABLE TASTE TEACH
THANK THEME THERE THING THREE TIGER TODAY TOKEN TOTAL TOUCH TOWER TRACK
TRADE TRAIL TRAIN TREAT TRIAL TRUST TRUTH UNDER UNION UNITY UPPER URBAN
USUAL VALUE VIDEO VISIT VITAL VOICE WATER WHEEL WHERE WHICH WHITE WHOLE
WOMAN WORLD WORTH WRITE WRONG YOUNG
""".split()


def load_generic_candidates(max_length: int, *, limit: int = 12_000) -> list[Candidate]:
    words = _load_wordfreq_words(limit) or _load_system_words(limit) or FALLBACK_WORDS
    cleaned: list[str] = []
    seen: set[str] = set()
    for word in words:
        answer = clean_answer(str(word))
        if 3 <= len(answer) <= max_length and answer not in seen:
            seen.add(answer)
            cleaned.append(answer)
    return [
        Candidate(answer=answer, priority=max(1, 8 - index // 5000), source="generic", is_family=False)
        for index, answer in enumerate(cleaned)
    ]


def _load_wordfreq_words(limit: int) -> list[str]:
    try:
        from wordfreq import top_n_list

        return list(top_n_list("en", limit))
    except Exception:
        return []


def _load_system_words(limit: int) -> list[str]:
    for path in (Path("/usr/share/dict/words"), Path("/usr/share/dict/web2")):
        if not path.exists():
            continue
        words = []
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            if line.isalpha():
                words.append(line)
            if len(words) >= limit:
                break
        if words:
            return words
    return []
